### ISSUE TITLE
During the Songs directory scan, ALL maps are marked as "Unranked"

### ISSUE THREAD

**Issue by TicClick** [naseweis520/osu-Sync#11]
https://github.com/naseweis520/osu-Sync/blob/master/osu!Sync/MainWindow.xaml.vb#L1395-L1453

**Comment by muekoeff** [comment]
**Occurrence.** After loading from cache file
**Possible cause.** Cache file doesn't contain information about rank-status

**Comment by muekoeff** [comment]
This has been fixed by disabling the cache.
