### ISSUE TITLE
System.IO.FileNotFoundException: Importing downloaded beatmap

### ISSUE THREAD

**Issue by muekoeff** [naseweis520/osu-Sync#18]
**Report**
[osu!Forum](https://osu.ppy.sh/forum/p/4546216)

**Comment by ghost** [comment]
System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) i've got this issue ;/

**Comment by muekoeff** [comment]
Thank you for re-reporting this issue.

I'm very sorry that I haven't fixed it yet and am currently trying to resolve this by emulating possible cases.

**Comment by muekoeff** [comment]
I'm not quite sure but I think that this issue is because of #15 which has just been fixed.
