### ISSUE TITLE
Every downloaded beatmap is 'invalid'

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#22]
Osu!Sync will say that ever beatmap is 'invalid' and give me the option to either skip it or cancel the whole download. Saying 'Yes' will cause it to hang for a bit before saying the same dialog for the next one, and so on and so forth. Saying 'No' will just make it cancel the download.
![syncerror](https://cloud.githubusercontent.com/assets/1988332/10556489/4929dc94-7452-11e5-973f-abbe929ee31f.png)

**Comment by muekoeff** [comment]
Weird. Yesterday it worked all fine.

**Comment by muekoeff** [comment]
**Reason.** [Bloodcat.com is currently down](http://isup.me/bloodcat.com)
**Solution.** In the settings, change your mirror to another one.

I will change the error message so that it's more clear what the problem is and how it can be fixed.
