### ISSUE TITLE
[1.0.0.8] Download Failed - False Negative report

### ISSUE THREAD

**Issue by BobbyL2k** [naseweis520/osu-Sync#25]
osu!Sync Version 1.0.0.8

When downloading songs which doesn't exits from bloodcat.

All the download report successful

![Message Box](http://i.imgur.com/e7JF8Xx.jpg)

Creates file with

```
* File not found or inaccessible!
```

in the osu! song directory.

**Comment by muekoeff** [comment]
That's new behaviour of Bloodcat. Thank you for reporting.
Will be fixed in the next update.

**Comment by muekoeff** [comment]
Fixed with 958869441c801898f3e42feacc5127195fa7b2b8
