### ISSUE TITLE
[1.0.0.8 - 1.0.0.9] Settings Page - Weird Image

### ISSUE THREAD

**Issue by BobbyL2k** [naseweis520/osu-Sync#27]
Is this suppose to happen?

![Screen Shot](http://i.imgur.com/iabjQ9m.jpg)

**Comment by muekoeff** [comment]
Actually yes, though I'll remove the header images soon.

**Comment by muekoeff** [comment]
Done with 31715b73b417ac9f17f66a2f366896f651654057
