### ISSUE TITLE
Add "Yes, for all"-button to certain dialogs

### ISSUE THREAD

**Issue by muekoeff** [naseweis520/osu-Sync#32]
![2aa867ec6a](https://cloud.githubusercontent.com/assets/3207399/15934092/82339dac-2e62-11e6-846b-27d89a646e43.png)

_Requested by Andrey_

**Comment by alpharou** [comment]
I second the idea. Maybe a config box which can disable that pop dialogs something like: For this dialog, auto answer YES or NO or do it manually. It messes with fullscreen programs a lot.

**Comment by muekoeff** [comment]
![Implemented "Yes, for all"](https://cloud.githubusercontent.com/assets/3207399/16156737/e3025598-34b5-11e6-944a-7e47c7da76cb.png)
[**Download** current development build](https://github.com/naseweis520/osu-Sync/files/320871/osu.Sync.1_0_0_13.Dev.zip)
