### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by hexxone** [naseweis520/osu-Sync#39]
Since bloodcat is offline I switched to the other mirror in the settings (osu.uu.gl) and was going to download a bigger set of maps (about 1,5k) when first, a "b-baka"-Exception window popped up mutliple times, then a Notepad with exception infos opened and the program crashed. I tried this 3 times with the same result. Here are the details:

===== osu!Sync Crash | 2017-09-07 01:53:37   =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp   |   osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"False","lastUpdateCheck":"20170907011634","version":"1.0.0.16"},"config":{"downloadMirror":"2","updateInterval":"3"},"language":{"code":"de_DE"},"system":{"cultureInfo":"de-DE","is64bit":"True","operatingSystem":"6.3.9600.0"}}

// Exception
System.NotSupportedException: WebClient unterstützt keine gleichzeitigen E/A-Vorgänge.
   bei System.Net.WebClient.ClearWebClientState()
   bei System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   bei osu_Sync.MainWindow.Importer_DownloadBeatmap()
   bei osu_Sync.MainWindow.Importer_Downloader_ToNextDownload()
   bei System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   bei System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kontorted** [comment]
A similar issue occurs when there are is no database to synchronize beatmaps from, and no beatmaps within the songs folder
Details can be found here: https://hastebin.com/faxinehaqa.scala

**Comment by muekoeff** [comment]
@Kontorted Thank you for reporting this issue. However, judging by your report I'd say that this is a separate bug. Please refer to the newly created issue #45.
