### ISSUE TITLE
Songs failing to import

### ISSUE THREAD

**Issue by ghost** [naseweis520/osu-Sync#46]
I'm trying to import a bunch of songs to my laptop but most of the songs fail. I've tried using the regular osu list file too and reinstalling both osu and osu!Sync. I've also tried different mirror in the import section and they fail as well.

**Comment by muekoeff** [comment]
Hello CaptainVianite,
thank you for reporting this problem.
Unfortunately I haven't been able to reproduce it.
Would it be possible that you name at least one of the songs which fail to be downloaded so that I can have a more in depth look at what might be the problem?

**Comment by ghost** [comment]
It finally worked for some reason? After several retries on different mirrors I got it to 50/55 downloaded so it wasn't an issue to just download the rest manually. I think it was because of the fact the songs came out a couple weeks ago. But if you can't reproduce it it's fine I'll report a more detailed problem if it happens again in a couple weeks. I used song packs from July and June.

**Comment by muekoeff** [comment]
I guess the available mirrors hadn't downloaded the missing songs at that time yet.
