### ISSUE TITLE
Exception when downloading beatmaps with Ripple mirror

### ISSUE THREAD

**Issue by CubieX** [naseweis520/osu-Sync#47]
I tied downloading from osu.uu.gl and Hexide, witch both game me an error (cant retrieve data, or something).
So I switched to Ripple.
That seemed to work at first, but I got "b-baka - Exception"s for every downloaded beatmap and after 6 maps, the screen was full of b-baka exceptions and the program froze.

The crash log is attached.
[2018-08-25 18.48.50.txt](https://github.com/naseweis520/osu-Sync/files/2320874/2018-08-25.18.48.50.txt)

So I can basically no longer use Osu!Sync at the moment....

**Comment by naseweis520** [comment]
Thank you for reporting this bug. Looks like I made a very stupid code mistake.
This won't take very long to fix.

**Comment by muekoeff** [comment]
Please excuse me belated reply. However, it looks like the issue isn't as simple as I expected it to be. At first I thought that I just made a typo somewhere but that doesn't seem to be the case.

Would you mind sending me your beatmap list file for testing purposes?

**Comment by MaxKruse** [comment]
Ripple's mirror no longer holds all ranked beatmaps, peppy forbid them from mass downloading. Only old maps (>5 months ish) are available. Instead of a file, you get a HTML page with an error on it.

**Comment by CubieX** [comment]
[BeatmapListMIII.zip](https://github.com/naseweis520/osu-Sync/files/2364345/BeatmapListMIII.zip)
Here you go.

**Comment by 60percentCaffeine** [comment]
Is this going to be fixed?

**Comment by 60percentCaffeine** [comment]
nvm Hexide is still up

**Comment by muekoeff** [comment]
To be honest, I'm unfortunately unable to reproduce this bug.
Does it still occur? Do you know which beatmap causes the application to crash?

**Comment by CubieX** [comment]
Doh. I should activate mail reminder or something...

It still ocurrs. Hexide and Ripple.
It's tons of beatmaps that cause it. Like, 90% fail with that exception.
I guess those serves only have a fraction of those beatmaps available And every fail causes that exception.
Here is a ist with maps taht failed today and caused that exception.
I tried both mirrors. Hexide, and the list was created by trying Ripple.
https://pastebin.com/raw/De5YGnGt

The affected PC runs Win 7 Pro x64.
I did not try it with my primary PC yet  (Win 10), as I usually sync from that to the Win7 one.

**Comment by muekoeff** [comment]
The problem seems to be having too many consecutive failing web requests though I still can't understand why the log file states `System.Windows.ResourceReferenceKeyNotFoundException`.

I've restructured the code for downloading beatmaps into two separate classes. But I still have to find a way to perform the webrequest asynchronously.
