### ISSUE TITLE
Updator problems

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#5]
Unless I'm just very impatient, the updater doesn't seem to work. It notifies me of an update just fine, and then downloads it. It asks me if I want to clear the folder, and I say yes. After that it just sits at "Verified Update Package" for a while, with the loading bar still moving, and the 'loading' mouse icon when you mouse over it. Apologies for no screenshots, but the folder's empty, and I can only download the updated version.
**UPDATE:** Tried it on another computer and it worked flawlessly. Only thing that changed was the OS (worked on win7, not on win8.) Sorry if that's not very helpful.

**Comment by muekoeff** [comment]
I think I know which problem you mention.
Did you update from ver. 0.0.0.8?

**Comment by Hay1tsme** [comment]
Yes, from 0.0.0.8 to 0.0.0.9

**Comment by muekoeff** [comment]
Well, in 0.0.0.8 there was a problem which could occure on some systems. If the automatic patch fails you have to download and replace the files from the update package manually. Path: http://j.mp/1NqSo2d

However, this bug should be fixed in ver. 0.0.0.9 and later. Sorry for the trouble.

**Comment by Hay1tsme** [comment]
It's okay, glad it got fixed! :)

**Comment by muekoeff** [comment]
Thank you very much. :)
