### ISSUE TITLE
Another update issue....

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#6]
I went to update from 0.0.0.9 to 0.0.0.10 on my Win8 laptop, and it was stuck at "Moving Files."
I went to the temp folder to see if I could just manually copy the files, but the only thing there was the Update Patcher

**Comment by muekoeff** [comment]
Hello again,
I've changed the unzipping progress of the updater and now use an extra library for it.
This should definitely fix this issue. :D
The new update patcher will automatically be downloaded at the next update, no user actions are required. If the problem occures again, please report it.
Thank you very much. :)

**Comment by muekoeff** [comment]
// Edit:
The latest update can't be patched because of an mistake I made. T_T
Please download it manually, instructions are in the changelog box.

**Comment by Hay1tsme** [comment]
Well, I downloaded the .11 version and haven't encountered any issues, but I guess we'll see the next time it gets an update x3

**Comment by muekoeff** [comment]
Yeah. :D
