### ISSUE TITLE
Scroll bar hard to grab

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#7]
I'm not sure if this even constitutes a bug report, but here we go...
I've noticed, for a while, that the scroll bar on the side of the window is sometimes tricky to grab. The reason being that, after a certain point (about 1/4th of the way across it) my mouse turns into the resize icon and can no longer be grabbed. This happens both on my Win7 Computer and my Win 8.1 Laptop
Unfortunately, Puush doesn't let me screen cap my mouse, so I can't really provide screen shots, but it's easy to reproduce.

**Comment by muekoeff** [comment]
Ok, fixed with latest commit. The scrollbar now has a small spacing to the border of the window.

**Comment by Hay1tsme** [comment]
Alright, I'll see how it works next release
