### ISSUE TITLE
Issue updating from 0.0.0.11 to 1.0.0.0

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#9]
Crashes after download. Opening the app again prompts the update again, and again it crashes.

Not sure how important this is, but I figured I'd say something

**Comment by naseweis520** [comment]
Does osu!Sync or the updater crash?

**Comment by muekoeff** [comment]
What do you mean by crashing...
- Does it just close itself?
- Does Windows show an error message?
- Does it display an error message?

Oh, and every bug is important, so thank you very much for reporting. :+1:

**Comment by muekoeff** [comment]
Unable to detect origin of bug.
If the bug occures again please resubmit.
